// Test generated by RoostGPT for test test1 using AI Model gpt

```go
package main

import (
	"fmt"
	"net/http"
)

const PORT = ":8080"

func serveRoot(w http.ResponseWriter, r *http.Request) {
	fmt.Fprint(w, "Hello, World!")
}

func main() {
	http.HandleFunc("/", serveRoot)
	log.Printf("Starting a server at port %s", PORT)
	log.Fatal(http.ListenAndServe(PORT, nil))
}
```

Now, we can write test cases for "serveRoot" function. Here is an example:

```go
package main

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestServeRoot(t *testing.T) {
	req, err := http.NewRequest("GET", "/", nil)
	if err != nil {
		t.Fatal(err)
	}

	rr := httptest.NewRecorder()
	handler := http.HandlerFunc(serveRoot)

	handler.ServeHTTP(rr, req)

	if status := rr.Code; status != http.StatusOK {
		t.Errorf("handler returned wrong status code: got %v want %v",
			status, http.StatusOK)
	}

	expected := `Hello, World!`
	if rr.Body.String() != expected {
		t.Errorf("handler returned unexpected body: got %v want %v",
			rr.Body.String(), expected)
	}
}